sqlite3:
  adapter: sqlite3
  database: acts_as_challenged.sqlite3

mysql:
  adapter: mysql2
  hostname: localhost
  username: root
  password:
  database: acts_as_challenged
  charset: utf8
  
postgresql:
  adapter: postgresql
  hostname: localhost
  username: postgres
  password:
  database: acts_as_challenged
  encoding: utf8
